name: Build Check

# Run this workflow on push or pull requests to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps to run in the build job
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js with the specified version
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use the version of Node.js your project requires
          cache: 'pnpm' # Cache pnpm dependencies

      # Step 3: Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Step 4: Install dependencies using pnpm
      - name: Install dependencies
        run: pnpm install

      # Step 5: Build the Next.js project
      - name: Build project
        run: pnpm run build

      # Optionally: Step 6 - Run tests
     # - name: Run tests
      #  run: pnpm run test
