name: Build Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          run_install: false

      # Step 2: Set up Node.js environment
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.15.0
          cache: "pnpm"

      # Step 4: Install dependencies using pnpm
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      # Step 5: Build the project
      - name: Build project
        run: pnpm run build
